# Generated by Django 2.1 on 2022-04-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
