# Generated by Django 4.0.2 on 2022-04-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc', '0002_auto_20220423_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
