# Generated by Django 4.0.3 on 2022-04-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('perks of being', 'Perks of being'), ('All the bright', 'All the bright'), ('The girl on the', 'The girl on the'), ('Django', 'Django')], max_length=100)),
            ],
        ),
    ]
