# Generated by Django 4.0.3 on 2022-04-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
